### ISSUE TITLE
Create ResourceHeader component

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon-addons-cloud#14]
This issue is to handle the creation of a new `ResourceHeader` component that's being used for consolidation in Control and Cloud.

**Comment by marijohannessen** [comment]
**Design**: [Sketch file](https://ibm.ent.box.com/file/270237414944)

The `ResourceHeader` is based heavily on the existing DetailPageHeader, so work can be based off that component.

The most complex variation of the component:

<img width="1244" alt="screen shot 2018-01-26 at 9 33 46 am" src="https://user-images.githubusercontent.com/5447411/35447007-1827fd28-027c-11e8-9eee-56e5a4ea351d.png">

- Breadcrumb(s)
- Logo/icon
- Title (sometimes w/ status)
- Sub info (up to 3 items it looks like)
- Status (up to 2)
- Stop/Play button
- Reboot button
- Maintenance link
- Actions inline drop-down
