### ISSUE TITLE
A11Y: InteriorLeftNav toggle not working when using keyboard

### ISSUE THREAD

**Issue by ashpc** [carbon-design-system/carbon-addons-cloud#21]
## Detailed description

Describe in detail the issue you're having. Is this a feature request (new component, new icon), a bug, or a general issue?

When navigating through the InteriorLeftNavItem using keyboard(tab), the toggle is not working as expected.

> Is this issue related to a specific component?

InteriorLeftNav

> What did you expect to happen? What happened instead? What would you like to see changed?

When I hit enter on the toggle for the InteriorLeftNav, it should close and when I hit enter again it should open. But once the InteriorLeftNav closes it doesn't open up when using keyboard.

> What browser are you working in?

Chrome and FF

> What version of the Carbon Design System are you using?

"carbon-addons-beta-react": "1.3.2",
    "carbon-addons-bluemix": "0.2.0",
    "carbon-components": "8.8.1",
    "carbon-components-react": "5.12.0",
    "carbon-icons": "6.1.0"

## Steps to reproduce the issue

1. Use tab to navigate through the items in the InteriorLeftNav and when you reach toggle option hit enter
2. If the InteriorLeftNav is open it will close and then hit enter again and it remains closed and never opens unless done through mouse.

## Add labels
Please choose the appropriate label(s) from our existing label list to ensure that your issue is properly categorized. This will help us to better understand and address your issue.
bug

**Comment by asudoh** [comment]
Hi @ashpc thank you for taking time to reporting this issue! I had a chance to quickly try to reproduce it on react.carbondesignsystem.com, but couldn’t reproduce it - What I did was hitting tab key until “Example Item 1” is highlighted and hitting Enter key twice - I see the section is expanded and the collapsed. Please don’t hesitate to speak up if I’m missing anything. Thanks!

**Comment by ashpc** [comment]
@asudoh when the focus is on the left nav toggle element `bx--interior-left-nav-collapse` and if you use the keyboard it collapses but if you kit enter again it fails to reopen again. I am abel to reproduce this issue even in react.carbondesignsystem.com. Let me know if you need more info on this.

**Comment by asudoh** [comment]
Thank you @ashpc for clarifying what you found!
