### ISSUE TITLE
CloudHeader: Menu Items not clickable in Firefox

### ISSUE THREAD

**Issue by davidgeorgeuk** [carbon-design-system/carbon-addons-cloud#31]
## Detailed description

Bug: When using Firefox (Developer Edition 59.0b9 (64-bit)) and the CloudHeader, the menu items under the menus (specifically the User menu) are not clickable. They work as expected in Chrome.

This is reproducible using [the storybook](http://cloud.carbondesignsystem.com/?selectedKind=CloudHeader&selectedStory=default&full=0&down=1&left=1&panelRight=0&downPanel=jbovenschen%2Fstorybook-addon-a11y%2Faddon-panel)

When hovering over a menu item, I expect the cursor to become a pointer, as it does in Chrome. I expect the links to be clickable.

Browser: Firefox (Developer Edition 59.0b9 (64-bit))
Version: carbon-addons-cloud@1.2.0

## Steps to reproduce the issue

1. Open [the storybook](http://cloud.carbondesignsystem.com/?selectedKind=CloudHeader&selectedStory=default&full=0&down=1&left=1&panelRight=0&downPanel=jbovenschen%2Fstorybook-addon-a11y%2Faddon-panel) for CloudHeader, using Firefox
2. Click the user icon.
3. Hover over the 'User 1' menu item

The cursor does not become a pointer.
The item is not clickable.
Note that the same sequence of actions works as expected using chrome

## Add labels
- bug

**Comment by joshblack** [comment]
Hey @davidgeorgeuk! These menus aren't meant to be functional, they're only meant to be used as an example of how the rendering would work for these menus. We can definitely try and update them, but this work would be considered low priority as the menus aren't meant to be used.

If I'm missing some context here, let me know btw! Just wanted to try and respond quickly here 😄

**Comment by davidgeorgeuk** [comment]
Hi @joshblack. I'm afraid it's not cosmetic, its actually a functional problem. I've identified this problem because for my team's use case, the component that goes in the menu should be clickable and it isn't in firefox. The problem is that whatever goes in the menu doesn't seem to be targetable for click events, making it useless as a menu.

Another way to demonstrate this is to compare the behaviour in chrome to that for FF for the following steps

1. Open [the storybook](http://cloud.carbondesignsystem.com/?selectedKind=CloudHeader&selectedStory=default&full=0&down=1&left=1&panelRight=0&downPanel=jbovenschen%2Fstorybook-addon-a11y%2Faddon-panel) for CloudHeader, using Firefox
2. Click the user icon.
3. Right click on the 'User 1' menu item and 'inspect' it

In Chrome, the inspector will jump to the 'User 1' list item. In Firefox, the inspector shows the storybook container. It is as if you clicked on the div underneath the menu.

I think that this has something to do with the fact that the dropdown gets absolutely positioned, but it lives *inside* the User button. The dropdown ends up in the overflow for the CloudHeader, and you can see it, but not click it.

Interestingly, if the button is replaced by a `<div>` this problem goes away.

**Comment by davidgeorgeuk** [comment]
On another inspection, I realise that the way that the menu gets absolutely positioned is actually part of the example, but there really needs to be a way of using this menu, particularly with the `renderUser` callback prop, that allows you to click the resulting user menu in Firefox. Is there another Carbon Component we should use in this place

**Comment by joshblack** [comment]
Hey @davidgeorgeuk! Thanks for providing more context, really appreciate it! Looking more into this morning 😄

**Comment by tw15egan** [comment]
I'll have a fix up in a PR shortly @davidgeorgeuk

**Comment by tw15egan** [comment]
@davidgeorgeuk PR is up, if you could verify that the changes fix your problem that would be great!

**Comment by davidgeorgeuk** [comment]
That is super, thank you @tw15egan . I confirm that this solves the problem for me, both in the storybook and in my product scenario.

**Comment by tw15egan** [comment]
Fix is available in v`1.2.1` 🍻
