### ISSUE TITLE
The left hidden menu is not accessible through tabbing

### ISSUE THREAD

**Issue by davidicus** [carbon-design-system/carbon-addons-cloud#43]
## Detailed description

If you were to click on the three lined icon on the left and try to tab into menu you are unable to. Nor can you shift+tab into it. I have even changed the span to be an anchor tab and added a tabindex attribute and am still unable to tab to item. 

Unsure if this is some weird issue with story book or the createPortal method. 

> Is this issue related to a specific component?

- CloudHeader

> What did you expect to happen? What happened instead? What would you like to see changed?

 - I expect when I open the menu that I would be able to tab into it. 

> What browser are you working in?

- Google Chrome

> What version of the Carbon Design System are you using?

- Latest. Can be seen in storybook demo

## Steps to reproduce the issue

1. Click on three lined menu
2. Try to tab
3. 😭 

## Additional information

![image](https://user-images.githubusercontent.com/1590966/39027095-f4655080-4415-11e8-9874-db0a589f6dbf.png)

## Add labels
Wish i could

**Comment by joshblack** [comment]
Going to close this as this work has been subsumed by the UI Shell work!
