### ISSUE TITLE
OrderSummaryListItem `text` property only supports string values

### ISSUE THREAD

**Issue by jrpomeroy** [carbon-design-system/carbon-addons-cloud#45]
There is a desire to add a tooltip to one of the items in the order summary but since it only wants a `String` this gives us trouble.  It would be nice if this could also support a `Node`.

**Comment by jrpomeroy** [comment]
This gets a little complicated, in the case of wanting to put a Tooltip in the OrderSummaryListItem, because the list item child nodes use a \<p\> tag and the Tooltip uses a \<div\> so you end up with a bunch of DOM nesting validation warnings in the browser console:

![image](https://user-images.githubusercontent.com/18622709/40019401-bd707726-5784-11e8-903c-f9c20c92a5e6.png)

Maybe the OrderSummaryListItem could use divs? Or is there some other suggested way around this?

**Comment by tw15egan** [comment]
Yeah we can just switch `OrderSummaryListItem` to be a `div` instead of `p` tags
